configurations:
  - sources:
      include:
        - Sources/
      exclude:
        - Sources/SparkIconTesting/
        - Sources/SparkIconSnapshotTesting/
    templates:
      - .sourcery/template/SparkAutoMockable.stencil
    output: Sources/SparkIconTesting/Generated/AutoMockable.generated.swift
    args:
      autoMockableImports: [Combine, SparkTheming, SparkTheme]
      autoMockableSPIImports: [SparkCommon, SparkCommonTesting, SparkThemingTesting]
      autoMockableTestableImports: [SparkIcon]
  - sources:
      include:
        - Sources/
      exclude:
        - Sources/SparkIconTesting/
        - Sources/SparkIconSnapshotTesting/
    templates:
      - .sourcery/template/SparkAutoMockTest.stencil
    output: Sources/SparkIconTesting/Generated/AutoMockTest.generated.swift
    args:
      autoMockableImports: [Combine, SparkTheming]
      autoMockableSPIImports: [SparkCommon, SparkCommonTesting, SparkThemingTesting]
      autoMockableTestableImports: [SparkIcon]
  - sources:
      include:
        - Sources/
      exclude:
        - Sources/SparkIconTesting/
        - Sources/SparkIconSnapshotTesting/
    templates:
      - .sourcery/template/SparkAutoPublisherTest.stencil
    output: Sources/SparkIconTesting/Generated/AutoPublisherTest.generated.swift
    args:
      autoMockableImports: [Combine, SparkTheming]
      autoMockableSPIImports: [SparkCommon, SparkCommonTesting, SparkThemingTesting]
      autoMockableTestableImports: [SparkIcon]
  - sources:
      include:
        - Sources/
      exclude:
        - Sources/SparkIconTesting/
        - Sources/SparkIconSnapshotTesting/
    templates:
      - .sourcery/template/SparkAutoViewModelStub.stencil
    output: Sources/SparkIconTesting/Generated/AutoViewModelStub.generated.swift
    args:
      autoMockableImports: [Combine, SparkTheming]
      autoMockableSPIImports: [SparkCommon, SparkCommonTesting, SparkThemingTesting]
      autoMockableTestableImports: [SparkIcon]
